name: CI #on Continous Integration

on:
  push:
  pull_request:

jobs:
  run_tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"

    name: Test on ${{ matrix.os }} (Python ${{ matrix.python-version }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Updated to v2

      - name: Set up Python
        uses: actions/setup-python@v2  # Updated to v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest 
        shell: bash  # Use bash shell for multiline commands

      - name: Run Tests
        run: pytest
